language: node_js
sudo: required
node_js:
- lts/*
cache:
  directories:
  - node_modules
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 47.105.40.207
install:
  - npm install
before_install:
- openssl aes-256-cbc -K $encrypted_77f76d6cdcd2_key -iv $encrypted_77f76d6cdcd2_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- chmod u+x *.sh
script:
-
after_success:
- ssh -o StrictHostKeyChecking=no root@47.105.40.207
  ' cd /data/www/
    && rm -rf ./backend
    && git clone git@github.com:Thawsoar/eggjs-service.git
    && mv eggjs-service backend 
    && cd backend
    && yarn install --production
    && yarn start --ignore-stderr
  '
env:
  global:
  - GH_REF: github.com/Thawsoar/eggjs-service.git
